### ISSUE TITLE
using rules without including the plugin gives tons of warnings

### ISSUE THREAD

**Issue by joeycozza** [fs-webdev/eslint-config-tree#1]
![Screen Shot 2019-06-24 at 9 04 35 AM](https://user-images.githubusercontent.com/3885959/60029865-2945a380-965f-11e9-8412-b39a4badfae3.png)

Just a heads up, by defining the rules of sonarjs here, but not including the plugin, you are forcing any consumer of eslint-config-tree to npm install and explicitly put sonarjs as a plugin in their eslint config. If the consumer doesn't put sonarjs in their eslint plugin list, they get a warning for every rule on every file being run (see screenshot).

It probably makes more sense to just include sonarjs in the plugin list here in eslint-config-tree, then everyone gets it without adding more work to for them.

**Comment by skye2k2** [comment]
I would, but then Code Climate crashes when it can't find it.

**Comment by joeycozza** [comment]
I guess if eslint-config-tree is always going to be used with sonarjs AND you ignore warnings in codeClimate then it isn't much of an issue.
